### ISSUE TITLE
RSE Bachelor Programme?

### ISSUE THREAD

**Issue by CaptainSifff** [the-teachingRSE-project/competencies#220]
What should a RSE Bachelor Programme look like? Do we need that? How do we give people research skills without a home domain where they can do research?

**Comment by BeastyBlacksmith** [comment]
1. We could have a high portion of elective subjects, where we expect to students to pick courses from different disciplines
2. We have pre-selected tracks (e.g. a RSE with a physics specialisation would be required to hear theoretical physics, but doesn't need to hear experimental physics)

**Comment by MakisH** [comment]
A typical STEM bachelor's contains some mathematics, some physics, (hopefully) some programming, and more fundamental science courses based on the general direction. This is nicely continuing what we learn in high school, where students are typically still in the very theoretical thinking mode. These fundamental courses also shape a student's identity, as it is maybe the first time they have actively selected something so important. Afterwards, and especially in the Master's, it mostly gets technical and eventually practical.

If we see RSEs as "researchers who also do software engineering", then we need to make them researchers first. And who could be best in giving them research foundations than a traditional program that prepares you to eventually continue doing research in some field?

I am not sure if we need an RSE Bachelor's Program, for the following reasons:

- That's what I know so far (bias)
- Graduates would not really have their own home domain
    - They would not really feel like scientists, they would not have a common identity
    - They would not be able to fall back into their home domain if they want to switch paths later on (18yo is too early and RSE too specific)
- If we focus too early on the technical/practical aspects, then this may not even be a B.Sc., but a more technical degree, which would then maybe question the future role of these graduates

Maybe it would be interesting to look at the historical evolution of study programs and see at which point a master's started, then a bachelor's, and how they differed from their most related programs. Recent examples would be Computer Science branching out of Mathematics, or more recently the Bioinformatics, Games Engineering etc at TUM ([degress at TUM CIT](https://www.cit.tum.de/en/cit/studies/degree-programs/)).

**Comment by mhagdorn** [comment]
When I was an undergrad I did a year of computational physics as part of my geophysics degree. This is really what set me on the path of becoming an RSE. So, I could imagine that the home domains could offer some courses to make the student into a computational biologist, physicist, chemist. They would gain the theoretical background for their home domain and some ideas of computational methods.

**Comment by CaptainSifff** [comment]
So this discussion moves to the notion, that we don't need an RSE bachelor?

**Comment by mhagdorn** [comment]
I think so. I agree with @MakisH, an RSE should have a home domain. Obviously a CS student might decide to become an RSE.

**Comment by MakisH** [comment]
> When I was an undergrad I did a year of computational physics as part of my geophysics degree. This is really what set me on the path of becoming an RSE.

Same for me: I studied Chemical Engineering (diploma, so not really B.Sc.+M.Sc., we had more time), but I took all the electives related to computational topics, which was what allowed me then to enter Computational Science & Engineering.

> So, I could imagine that the home domains could offer some courses to make the student into a computational biologist, physicist, chemist. They would gain the theoretical background for their home domain and some ideas of computational methods.

:+1:

> I think so. I agree with @MakisH, an RSE should have a home domain. Obviously a CS student might decide to become an RSE.

Maybe the TUM B.Sc. CS is interesting: You have to select an application direction as minor, which covers several electives. This includes various STEM fields. See the [Anwendungsfächer](https://www.cit.tum.de/en/cit/studium/studiengaenge/bachelor-informatik/).

> So this discussion moves to the notion, that we don't need an RSE bachelor?

We currently have **two main ways of becoming an RSE**:

- Studying a home domain and getting computational electives
- Studying CS and getting application electives

What I would be more concerned with would be **increasing/focusing these electives that both sides take.**

**To suggest needing an RSE bachelor's, I think we first need to prove the current ways insufficient / imperfect, or a field so developed, that it becomes its own distinct fundamental field.** I understand that we are not at this point yet, and we may not even ever be, because RSE is meant to be a bridge between CS and "home domain". Similarly for CSE: There are already many M.Sc. CSE and related, but barely any B.Sc. CSE ([SimTech](https://www.simtech.uni-stuttgart.de/sc/study-program/) in Stuttgart is one of the first).

But I will be very happy to be shown that I am just lacking imagination here!

**Comment by CaptainSifff** [comment]
It's not that I have good ideas....
I just think that coming up with a good idea for a bachelor programme has the deeper benefit of endowing identity to us as RSEs that reaches a bit deeper....
