### ISSUE TITLE
G20 wording

### ISSUE THREAD

**Issue by knarrff** [the-teachingRSE-project/competencies#300]
The text currently says this:

"while the majority of researchers come from G20 countries (88.8%)."

I would assume so (the majority), given that the countries represented by the G20 combined have two-thirds of the global population. Now, 66% isn't 88%, but the sentence makes it sound as "the majority" alone already would be a skew.

An alternative explanation could be that what meant is really "only the countries within the G20" (which would exclude countries within the EU and the AU that are not themselves part of the G20, as both the EU and the AU are member of the G20), but then we should give a number to compare the 88% to: that of the percentage of population within "only the **countries** that are member of the G20" (compared to global population).

**Comment by CaptainSifff** [comment]
@michelemartone , @jngrad, @mhagdorn, any opinions here?

**Comment by jngrad** [comment]
That's a fair point. One could rewrite the sentence to "women account for 33.3% of all researchers and G20 countries account for 88.8% of all researchers in 2018."

Mentioning "2018" is relevant here, since the African Union didn't join G20 until 2023. The list of G20 members and guest members fluctuates over time. In fact, page 740 of `Schneegans2021` defines G20 as:
> Argentina; Australia; Brazil; Canada; China; France; Germany; India; Indonesia; Italy; Japan; Korea, Rep.; Mexico; Russian Federation; Saudi Arabia; South Africa; Turkey; United Kingdom; United States of America; European Union

I'm not that well-versed into social studies, and I have a feeling we might not be using the G20 metric in the way it is intended to be used. We could write in a footnote the aforementioned definition of G20 and sum their populations. But then, hypothetically, let's say there is a follow-up `Schneegans2025`  report, what should we then write in a follow-up RSE paper or talk? G20 countries will account for x% of all researchers, but the list of countries will have changed too, and will be a lot more diverse.

**Comment by knarrff** [comment]
I would argue: what is the question we want to raise here or the fact we want to highlight? Maybe we can do the same without using the G20, especially if that really fluctuates that much. It seems like what we want to look at is essentially the researchers/population ratio in different parts of the world - this seems to be in line with the original argument. But do we want to really look deeper into this? We would have the numbers (e.g. http://data.uis.unesco.org/index.aspx?queryid=3685) and even graphs (e.g. http://chartsbin.com/view/1124) and it would be interesting, but a bit out of scope for this paper I suppose.

**Comment by mhagdorn** [comment]
I was trying to say that research is dominated by the Global North. It stems from the critique that we only mentioned white men and thereby excluded everybody else. We could certainly make the sentence

> This imbalance is even more pronounced in SE with a majority of developers identifying as white male

stronger by changing it to 

> This imbalance is even more pronounced in SE with the vast majority of developers identifying as white male

**Comment by knarrff** [comment]
Sorry to be picky.   Aren't these different statements? "white men" is different from "G20" which is again different from "global north".

I would like to avoid the term "global north" and "global south" here. First of all, to a lot of people they suggest "northern and southern hemisphere", which isn't how those are defined. And when you look at definitions, e.g.

"_as Rigg also highlights, the term should not be taken too literally, with the equator dividing the world in two. Instead, it  should be understood in the wider context of globalization – or global capitalism, in the case of Arif Dirlik’s reflection. In most cases it then becomes related to an economic division between rich(er) and poor(er) countries, with most people in the so-called Global South actually living in the northern hemisphere (for example, in India and China)_"

It looks like using these terms here would essentially say "there is an imbalance between countries that are richer and countries that are poorer in terms of researchers they (can) effort", which is hardly surprising, but also could be said more directly without using those terms.

**Comment by mhagdorn** [comment]
I did exactly mean Global North and South as expanded in your quote. Essentially I want to say there is an overrepresentation of rich people in academia in general which is further exacerbated in computing where most people are white male. This imbalance is a problem because among other things it leads to biases. We don't need to go into the causes for this imbalance. I don't think just saying that is a consequence of some countries being richer than others is just pointing out another symptom.  And yes, if you ask me it has to do with colonialism and hegemonic culture. As I said, I don't want this to be a political statement. I just want to point out the fact that this over/under-representation exists. We need to be aware of it and, I think, attempt to reduce it. 

I am not wedded to the formulation and am happy if someone can come up with a better one to express this fact.

**Comment by knarrff** [comment]
Something we could do here to also connect to the topic of the paper is, instead of pointing to "global N/S" to point to financial possibilities (because that is really what the definition of global N/S is), and give an example of how RSEs can help here: with pricing schemes that take this into account, like the Carpentries. They use the world bank income by region measure: https://datatopics.worldbank.org/world-development-indicators/the-world-by-income-and-region.html.

**Comment by CaptainSifff** [comment]
The other route, would be instead of financial imbalance you make the argument along the line of social imbalance. 
https://www.nature.com/articles/s41562-022-01425-4

**Comment by knarrff** [comment]
We could. I am not that familiar with the arguments in that direction. I do find it natural on first instinct that children on average tend to imitate their parents, unconsciously maybe even. This is not only true for academics, but most professions I would think.

**Comment by mhagdorn** [comment]
> The other route, would be instead of financial imbalance you make the argument along the line of social imbalance. https://www.nature.com/articles/s41562-022-01425-4

This paper is specific to the US. I think the Schneegans2021 is still the right report to quote. Looking at the table 1.3, page 93, we could reformulate the sentence

while the majority of researchers come from high income countries (60.3%).
